Major update for Prelude SIEM 5.0
Rewrite for Prelude SIEM 5.0:
- Use docker's secrets management mechanism
- Track centos:7 inside Dockerfiles instead of centos:latest
- Require a recent enough version of docker/docker-compose
- Move prewikka-crontab to a separate container
- Reduce image size by reducing the number of layers
- Use docker build's --squash option whenever its possible
- Improve password management inside the containers
- Send httpd's error_log to docker's logs management system
- Update configuration files to match content from upstream
- Improve conf reuse between production/development environments
- Fix missing dependencies for some components

diff --git a/files/usr/bin/start-prelude-manager b/files/usr/bin/start-prelude-manager
--- a/files/usr/bin/start-prelude-manager
+++ b/files/usr/bin/start-prelude-manager
@@ -2,25 +2,25 @@
 
 set -eu
 
-echo "Substituting variables"
-alerts_db_pass=`printf "%q" "${ALERTS_DB_PASS}"`
-sed -i  -e "s$(printf '\001')@ALERTS_DB_PASS@$(printf '\001')${alerts_db_pass}$(printf '\001')g"  \
-        /etc/prelude-manager/prelude-manager.conf
-
-echo "Storing the registration password"
-printf "${SENSORS_PASS}" > /prelude-registration
+echo "Preparing files required to access the database"
+ALERTS_DB_PASS=$(cat "${ALERTS_DB_PASSWORD_FILE}")
+touch                                                            ~root/.pgpass
+chmod 0600                                                       ~root/.pgpass
+chown root:root                                                  ~root/.pgpass
+printf "db-alerts:5432:prelude:prelude:%s\n" "$ALERTS_DB_PASS" > ~root/.pgpass
 
 echo "Creating the 'prelude-manager' profile"
 prelude-admin add "prelude-manager" --uid 0 --gid 0 || echo "Profile already exists"
 
 echo "Starting a registration server in the background"
-/usr/bin/prelude-admin registration-server prelude-manager --passwd-file=/prelude-registration --keepalive --no-confirm &
+/usr/bin/prelude-admin registration-server prelude-manager "--passwd-file=${SENSORS_PASSWORD_FILE}" --keepalive --no-confirm &
 sleep 1
+
 
 # Wait for the database to come online
 while [ true ]; do
     echo "Waiting for the IDMEF database to come online..."
-    res=`PGPASSWORD="${ALERTS_DB_PASS}" psql -U prelude -h db-alerts -Antq -c '\d' >/dev/null && echo "OK" || echo "NOK"`
+    res=`psql -U prelude -h db-alerts -Antq -c '\d' >/dev/null && echo "OK" || echo "NOK"`
     if [ "$res" = "OK" ]; then
         break
     fi
@@ -28,13 +28,10 @@ while [ true ]; do
 done
 
 # Create the alerts' database model if needed
-if [ -f /usr/share/libpreludedb/classic/pgsql.sql ] && [ -x /usr/bin/psql ]; then
-    #/usr/share/libpreludedb/classic/pgsql.sql
-    tables=`PGPASSWORD="${ALERTS_DB_PASS}" psql -U prelude -h db-alerts -Antq -c '\d'`
-    if [ -z "$tables" ]; then
-        echo "Initializing alerts' database"
-        PGPASSWORD="${ALERTS_DB_PASS}" psql -U prelude -h db-alerts -Antq -c '\i /usr/share/libpreludedb/classic/pgsql.sql'
-    fi
+tables=`psql -U prelude -h db-alerts -Antq -c '\d'`
+if [ -z "$tables" ]; then
+    echo "Initializing alerts' database"
+    psql -U prelude -h db-alerts -Antq -c '\i /usr/share/libpreludedb/classic/pgsql.sql'
 fi
 
 echo "Starting prelude-manager"
diff --git a/files/usr/bin/start-prewikka b/files/usr/bin/start-prewikka
--- a/files/usr/bin/start-prewikka
+++ b/files/usr/bin/start-prewikka
@@ -2,12 +2,15 @@
 
 set -eu
 
-echo "Substituting variables"
-alerts_db_pass=`printf "%q" "${ALERTS_DB_PASS}"`
-gui_db_pass=`printf "%q" "${GUI_DB_PASS}"`
-sed -i  -e "s$(printf '\001')@ALERTS_DB_PASS@$(printf '\001')${alerts_db_pass}$(printf '\001')g"  \
-        -e "s$(printf '\001')@GUI_DB_PASS@$(printf '\001')${gui_db_pass}$(printf '\001')g"  \
-        /etc/prewikka/prewikka.conf
+echo "Preparing files required to access the database"
+ALERTS_DB_PASS=$(cat "${ALERTS_DB_PASSWORD_FILE}")
+GUI_DB_PASS=$(cat "${GUI_DB_PASSWORD_FILE}")
+touch                                                            ~root/.pgpass
+chmod 0600                                                       ~root/.pgpass
+chown root:root                                                  ~root/.pgpass
+printf "db-alerts:5432:prelude:prelude:%s\n" "$ALERTS_DB_PASS" > ~root/.pgpass
+printf "db-gui:5432:prewikka:prewikka:%s\n"  "$GUI_DB_PASS"   >> ~root/.pgpass
+install -o apache -g apache -m 0600 ~root/.pgpass ~apache/
 
 # Make sure we're not confused by old, incompletely-shutdown httpd
 # context after restarting the container.  httpd won't start correctly
@@ -17,7 +20,7 @@ rm -rf /run/httpd/* /tmp/httpd*
 # Wait for the databases to come online
 while [ true ]; do
     echo "Waiting for the IDMEF database to come online..."
-    res=`PGPASSWORD="${ALERTS_DB_PASS}" psql -U prelude -h db-alerts -Antq -c '\d' >/dev/null && echo "OK" || echo "NOK"`
+    res=`psql -U prelude -h db-alerts -Antq -c '\d' >/dev/null && echo "OK" || echo "NOK"`
     if [ "$res" = "OK" ]; then
         break
     fi
@@ -26,7 +29,7 @@ done
 
 while [ true ]; do
     echo "Waiting for the GUI database to come online..."
-    res=`PGPASSWORD="${GUI_DB_PASS}" psql -U prewikka -h db-gui -Antq -c '\d' >/dev/null && echo "OK" || echo "NOK"`
+    res=`psql -U prewikka -h db-gui -Antq -c '\d' >/dev/null && echo "OK" || echo "NOK"`
     if [ "$res" = "OK" ]; then
         break
     fi
